### ISSUE TITLE
Revisit multithreading Shutdown() in destructors.

### ISSUE THREAD

**Issue by MikeHopcroft** [BitFunnel/BitFunnel#143]
Currently we disallow Shutdown() in destructors. This makes it hard to write RAII code.

**Comment by danluu** [comment]
I think the lack of RAII makes it very hard to write exception safe code. We should probably talk about this when I'm back in town, but I think we'll both be on the same page about this.

**Comment by danluu** [comment]
I have a fix for the obvious cases of this in the branch we have outstanding, but we still have the problem that shutting down a Recycler cleanly requires waiting for the thread the Recycler is running in to finish. One simple way to do this would be to have Recycler own its thread, to avoid having the owner of Recycler call Shutdown and then wait for the Recycler to finish.
