### ISSUE TITLE
`ChunkEnumerator` segfaults when we request thread count > 1

### ISSUE THREAD

**Issue by hausdorff** [BitFunnel/BitFunnel#248]
Clean build on commit `733972e`, OS X 10.10.2, `Apple LLVM version 6.1.0 (clang-602.0.53)`, targeting x86_64-apple-darwin14.1.0.

When we run simple benchmarks with more than 1 ingestor thread, BitFunnel crashes. The reason is because the `TaskDistributorThread`s are calling `ITaskProcessor.ProcessTask`; but, the `ITaskProcessor`s that it has references to were destructed at the end of `ChunkEnumerator`'s constructor. You can see this clearly on cursory inspection of this code:

```
    ChunkEnumerator::ChunkEnumerator(
        IChunkManifestIngestor const & manifest,
        size_t threadCount)
    {
        std::vector<std::unique_ptr<ITaskProcessor>> processors;
        for (size_t i = 0; i < threadCount; ++i) {
            processors.push_back(
                std::unique_ptr<ITaskProcessor>(
                    new ChunkTaskProcessor(manifest)));
        }

        if (threadCount > 1)
        {
            m_distributor = Factories::CreateTaskDistributor(processors, manifest.GetChunkCount());
        }
        else
        {
            // The threadCount == 1 case is implemented to simplify debugging.
            for (size_t i = 0; i < manifest.GetChunkCount(); ++i) {
                processors[0]->ProcessTask(i);
            }
        }
    }
```

We will probably want to move this out of local scope of the constructor, and put it somewhere more permanent.

**Comment by MikeHopcroft** [comment]
I wanted to unblock you quickly so I committed a change that passes all unit tests, but I did not try to replicate your specific scenario.

**Comment by hausdorff** [comment]
This is nearly identical to the change I have locally, so this works.
