### ISSUE TITLE
REPL should display an error when parsing a chunk file fails, instead of killing itself

### ISSUE THREAD

**Issue by hausdorff** [BitFunnel/BitFunnel#257]
Right now if a chunk file contains nonsense, `NullLogger::Abort` is called and the process terminates. This makes it difficult to know what's wrong, particularly since the error message simply says `"NullLogger::Abort()"`.

It seems to me that in this case we should display a warning explaining which file failed to be parsed, and simply continue along in the REPL.

**Comment by MikeHopcroft** [comment]
This is a special case of #258.

**Comment by hausdorff** [comment]
Ok, let's close this then.
