### ISSUE TITLE
Implement multiple shards

### ISSUE THREAD

**Issue by danluu** [BitFunnel/BitFunnel#291]
See #288, #290, and [this post](http://bitfunnel.org/row-table-analysis/) by @MikeHopcroft for the reasons this is necessary.

We currently make a default `ShardDefintion` that gives us one shard. To handle multiple shards, we'll have to do the following:

* ConfigureFor*` in `Ingestor` could load a `ShardDefinition` from the `FileManager`.
* The `ShardDefinition` stream constructor and write method will need to be ported.
* `FileManager` will need its `ShardDefinition` stuff ported.
* We'll have to make a `ShardDefinition` file.

After doing the port, we'll have to have a step that creates a `ShardDefinition` between running `StatisticsBuilder` and running `TermTableBuilder`.

**Comment by MikeHopcroft** [comment]
Note that we will not do a straight port of ShardDefinition. It has other columns that are no longer needed.

Sent from my Windows Phone
________________________________

**Comment by danluu** [comment]
Starting to look into this. I'm going to track issues here since we don't really do in-depth commit messages.

One bug is that, if you switch

~~~
-            Factories::CreateTermTableCollection();
+            Factories::CreateTermTableCollection(1);
~~~

this causes tests to fail. In theory, this change shouldn't make any difference.

**Comment by danluu** [comment]
Actually, maybe that's working as intended... the issue is that we have code that expects to "manually" add a single TermTable. Porting that code to be multi-shard requires constructing the TermTable for each shard.

**Comment by danluu** [comment]
After a few fixes, some internal unit tests pass with multiple shards. It looks like we can ingest with multiple shards at least in one basic case (where all term tables are identical).

However, StatisticsBuilder doesn't have any concept of sharding and TermTableBuilderTool hardcodes a single shard:

~~~
                ShardId shard = 0;
~~~

**Comment by danluu** [comment]
After a few more fixes, TermTableBuilderTool creates multiple TermTables, but Ingestor only creates one shard despite seemingly making shards based on ShardDefinition:

~~~
        // Create shards based on shard definition in m_shardDefinition..
        for (ShardId shardId = 0; shardId < m_shardDefinition.GetShardCount(); ++shardId)
        {
            std::cout << "Creating shard: " << shardId << std::endl;
            m_shards.push_back(
                std::unique_ptr<Shard>(
                    new Shard(shardId,
                              GetRecycler(),
                              GetTokenManager(),
                              termTables.GetTermTable(shardId),
                              docDataSchema,
                              m_sliceBufferAllocator,
                              m_sliceBufferAllocator.GetSliceBufferSize())));
        }
~~~

**Comment by danluu** [comment]
After more fixes, Ingestor now creates multiple shards but we crash on querying because the RowSet claims that we only have one shard, so it doesn't keep a set of offsets for each shard.

**Comment by danluu** [comment]
After fixing that, we're back to having a test that runs without crashing that reports false positives. I suspect I'm done for the day other than maybe getting something done on the bus. If I had to guess, I'd guess that we're doing something bad on ingestion, but the problem could just as easily be in the query path.

**Comment by danluu** [comment]
I don't think I have time to get to much more tonight, so I'm dumping state here for now.

If we set up the ShardDefinition such that shard 0 is empty and shard 1 is not empty, the TermTableBuilder claims that we have explicit terms in TermTable-0 (after fixing #375) and no explicit terms in TermTable-1.

It appears that all explicit terms are hardcoded to appear in TermTable-0.

~~~
Total build time: 4.7491e-05 seconds.
===================================
RowAssigner for rank 0
  No terms
  Terms
    Total: 70
    Adhoc: 0
    Explicit: 0
    Private: 70

  Rows
    Total: 1073
    Adhoc: 1000
    Shared Explicit: 0
    Private Explicit: 70
    Explicit: 73

  Bytes per document: 134.5


  Densities in explicit shared rows
    Mean: nan
    Min: nan
    Max: nan
    Variance: 1
~~~

~~~
Starting TermTable build.
Total build time: 0.000134527 seconds.
===================================
RowAssigner for rank 0
  Terms
    Total: 3555
    Adhoc: 3418
    Explicit: 0
    Private: 137

  Rows
    Total: 1140
    Adhoc: 1000
    Shared Explicit: 0
    Private Explicit: 137
    Explicit: 140

  Bytes per document: 142.875


  Densities in explicit shared rows
    Mean: nan
    Min: nan
    Max: nan
    Variance: 1

===================================
~~~

**Comment by danluu** [comment]
I'm going to mark this as closed and put future sharding issues in their own bugs because it's already hard to make sense of this long issue and will get harder as we pile more info into this. Sharding isn't 100%, but the basic implementation is in and it's no worse than some other stuff we have in.
