### ISSUE TITLE
TermTableBuilder crashes when TermTreatment specifies configurations (ranks) that don't get hit by terms from sample corpus

### ISSUE THREAD

**Issue by danluu** [BitFunnel/BitFunnel#314]
I'm not sure exactly what's going on, but it appears that we can call `AddRowId` in a rank without necessarily assigning a number of rows to that rank.

**Comment by MikeHopcroft** [comment]
TermTable::AddRowId() does not increase the number of rows in a rank. It merely adds the RowId to the set of row ids associated with a Term after a call to TermTable::OpenTerm(). The number of rows in a rank is set via the TermTable::SetRowCounts() method.

**Comment by danluu** [comment]
Fixed by 	4ebc063. Note that this fix means that we can create ranks that end up never being used if we don't have phrases.

The fundamental issue here is that we create a set of TermTreatments for each `idf` between 0 (1?) and the max idf. We then do "stuff" based on the sample part of the corpus that we build the `TermTable` with. It's possible that the sample has no terms with some idf values, which would cause multiple problems:

1. A few different asserts fired
2. 0 adHoc rows were allocated for some ranks, even though those ranks could potentially get hit via phrase queries because phrase queries have a computed `idf` that doesn't necessarily have to appear in the `DocumentFrequencyTable`.

The fix here removes the asserts from (1) and assigns rows appropriately in order to fix (2). This means that we can possibly allocate rows that can never get used. A more comprehensive fix could examine possible phrases to ensure that we never allocate rows that can't get used, but I think that's a relatively minor edge case compared to other issues that our system currently has. I'll file a bug on that to track it, but I suspect we'll never get around to fixing that.
