### ISSUE TITLE
Unreasonable results when running "Optimal" TermTableTreatment on GOV2

### ISSUE THREAD

**Issue by danluu** [BitFunnel/BitFunnel#385]
~~~
idf 0: 1 ==> private row
idf 0.1: 0.794328 ==> private row
idf 0.2: 0.630957 ==> private row
idf 0.3: 0.501187 ==> private row
idf 0.4: 0.398107 ==> private row
idf 0.5: 0.316228 ==> private row
idf 0.6: 0.251189 ==> private row
idf 0.7: 0.199526 ==> private row
idf 0.8: 0.158489 ==> private row
idf 0.9: 0.125893 ==> private row
idf 1: 0.1 ==> private row
idf 1.1: 0.0794328 ==> 100000: snr: 0.0934714, qw: 0.03125, bits: 0.03125, dq: 1024
idf 1.2: 0.0630957 ==> 100000: snr: 0.0776402, qw: 0.03125, bits: 0.03125, dq: 1024
idf 1.3: 0.0501187 ==> 100000: snr: 0.066212, qw: 0.03125, bits: 0.03125, dq: 1024
idf 1.4: 0.0398107 ==> 100000: snr: 0.0578933, qw: 0.03125, bits: 0.03125, dq: 1024
idf 1.5: 0.0316228 ==> 100000: snr: 0.0517766, qw: 0.03125, bits: 0.03125, dq: 1024
idf 1.6: 0.0251189 ==> 100000: snr: 0.047231, qw: 0.03125, bits: 0.03125, dq: 1024
idf 1.7: 0.0199526 ==> 100000: snr: 0.0438179, qw: 0.03125, bits: 0.03125, dq: 1024
idf 1.8: 0.0158489 ==> 100000: snr: 0.0412311, qw: 0.03125, bits: 0.03125, dq: 1024
idf 1.9: 0.0125893 ==> 100000: snr: 0.0392544, qw: 0.03125, bits: 0.03125, dq: 1024
idf 2: 0.01 ==> 100000: snr: 0.037733, qw: 0.03125, bits: 0.03125, dq: 1024
idf 2.1: 0.00794328 ==> 100000: snr: 0.0365553, qw: 0.03125, bits: 0.03125, dq: 1024
idf 2.2: 0.00630957 ==> 100000: snr: 0.0356389, qw: 0.03125, bits: 0.03125, dq: 1024
idf 2.3: 0.00501187 ==> 100000: snr: 0.0349232, qw: 0.03125, bits: 0.03125, dq: 1024
idf 2.4: 0.00398107 ==> 100000: snr: 0.0343622, qw: 0.03125, bits: 0.03125, dq: 1024
~~~

It's possible that this is technically correct, but it seems implausible that we just happen to get the same DQ for all of these and that the DQ is 1024. Furthermore, it's implausible that we could get reasonable results by producing a single rank 6 row for every type of term.

Note that this is without sharding, so we can probably "fix" this by sharding, but this indicates that there's some set of inputs for which we produce quite unreasonable outputs without any sort of error or warning.

The `Expermental` TermTreatment, which is allegedly identical, does not produce this configuration of all rank 6 rows.

More generally, before we published the paper, I fixed a lot of bugs in the `Optimal` treatment and was pretty sure there were bugs remaining because I could produce cases where `Optimal` and `Experimental` returned substantially different results, which shouldn't be the case unless at least one of the two implementations has a bug.

**Comment by danluu** [comment]
It's possible that I introduced this bug while adding plumbing for sharding, but if so, it's curious that `Experimental` produces a different and less obviously unreasonable result.

**Comment by MikeHopcroft** [comment]
Check to see whether you may have been running with SNR=0. I noticed that prior to my commit ce929912f46c5f659305a6169855e858a552ff93, the default value for SNR in the TermTableBuilder was 0. Here are the results that I get from my build:

D:\git\BitFunnel\build-msvc\tools\BitFunnel\src\Release>D:\git\BitFunnel\build-msvc\tools\BitFunnel\src\Release\BitFunnel termtable ^
More?     d:\data\work\GX000\BitFunnel\config ^
More?     0.1 ^
More?     Optimal
Loading files for TermTable build: 0
idf 0: 1 ==> private row
idf 0.1: 0.794328 ==> private row
idf 0.2: 0.630957 ==> private row
idf 0.3: 0.501187 ==> private row
idf 0.4: 0.398107 ==> private row
idf 0.5: 0.316228 ==> private row
idf 0.6: 0.251189 ==> private row
idf 0.7: 0.199526 ==> private row
idf 0.8: 0.158489 ==> private row
idf 0.9: 0.125893 ==> private row
idf 1: 0.1 ==> private row
idf 1.1: 0.0794328 ==> 000101: snr: 19.081, qw: 1.25, bits: 1.04433, dq: 0.766043
idf 1.2: 0.0630957 ==> 000101: snr: 10.2754, qw: 1.25, bits: 0.880957, dq: 0.908103
idf 1.3: 0.0501187 ==> 000002: snr: 20.143, qw: 1.99882, bits: 1.00237, dq: 0.49911
idf 1.4: 0.0398107 ==> 000002: snr: 10.9891, qw: 1.99882, bits: 0.796214, dq: 0.628342
idf 1.5: 0.0316228 ==> 100002: snr: 11.0742, qw: 2.02364, bits: 0.663706, dq: 0.744547
idf 1.6: 0.0251189 ==> 010002: snr: 14.4854, qw: 2.02036, bits: 0.564877, dq: 0.876228
idf 1.7: 0.0199526 ==> 010002: snr: 12.1785, qw: 1.99118, bits: 0.461552, dq: 1.0881
idf 1.8: 0.0158489 ==> 010002: snr: 10.6724, qw: 1.94951, bits: 0.379479, dq: 1.35172
idf 1.9: 0.0125893 ==> 000003: snr: 18.8497, qw: 2.72846, bits: 0.377678, dq: 0.970424
idf 2: 0.01 ==> 000003: snr: 13.7174, qw: 2.68815, bits: 0.3, dq: 1.24001
idf 2.1: 0.00794328 ==> 100003: snr: 46.858, qw: 2.3353, bits: 0.269548, dq: 1.58862
idf 2.2: 0.00630957 ==> 100003: snr: 43.335, qw: 2.20081, bits: 0.220537, dq: 2.06032
idf 2.3: 0.00501187 ==> 100003: snr: 40.7479, qw: 2.06433, bits: 0.181606, dq: 2.66742
idf 2.4: 0.00398107 ==> 100012: snr: 30.2697, qw: 1.51401, bits: 0.190334, dq: 3.4702
idf 2.5: 0.00316228 ==> 000004: snr: 35.9602, qw: 2.78265, bits: 0.126491, dq: 2.84107
idf 2.6: 0.00251189 ==> 000022: snr: 22.9282, qw: 1.80275, bits: 0.150587, dq: 3.68364
idf 2.7: 0.00199526 ==> 000022: snr: 18.5313, qw: 1.75221, bits: 0.119636, dq: 4.77037
idf 2.8: 0.00158489 ==> 000022: snr: 14.9316, qw: 1.71052, bits: 0.0950434, dq: 6.15105
idf 2.9: 0.00125893 ==> 000022: snr: 11.9998, qw: 1.67641, bits: 0.0755038, dq: 7.90044
idf 3: 0.001 ==> 000004: snr: 10.4102, qw: 2.61834, bits: 0.04, dq: 9.54803
idf 3.1: 0.000794328 ==> 000032: snr: 46.2042, qw: 1.46774, bits: 0.0635273, dq: 10.7249
idf 3.2: 0.000630957 ==> 000032: snr: 40.1079, qw: 1.43534, bits: 0.0504646, dq: 13.8057
idf 3.3: 0.000501187 ==> 000212: snr: 32.6453, qw: 0.927134, bits: 0.0601098, dq: 17.9437
idf 3.4: 0.000398107 ==> 000212: snr: 27.9148, qw: 0.902723, bits: 0.0477523, dq: 23.1981
idf 3.5: 0.000316228 ==> 000212: snr: 23.6145, qw: 0.883098, bits: 0.0379343, dq: 29.851
idf 3.6: 0.000251189 ==> 000212: snr: 19.7823, qw: 0.86736, bits: 0.0301344, dq: 38.2593
idf 3.7: 0.000199526 ==> 000212: snr: 16.4283, qw: 0.854764, bits: 0.023938, dq: 48.8727
idf 3.8: 0.000158489 ==> 000212: snr: 13.5396, qw: 0.844698, bits: 0.0190155, dq: 62.2575
idf 3.9: 0.000125893 ==> 000212: snr: 11.0862, qw: 0.836664, bits: 0.015105, dq: 79.1274
idf 4: 0.0001 ==> 002112: snr: 45.189, qw: 0.445418, bits: 0.0239937, dq: 93.5696
idf 4.1: 7.94328e-05 ==> 002112: snr: 40.4451, qw: 0.437476, bits: 0.0190599, dq: 119.929
idf 4.2: 6.30957e-05 ==> 002112: snr: 35.7276, qw: 0.431144, bits: 0.0151405, dq: 153.193
idf 4.3: 5.01187e-05 ==> 002112: snr: 31.1553, qw: 0.426099, bits: 0.0120269, dq: 195.135
idf 4.4: 3.98107e-05 ==> 002112: snr: 26.8337, qw: 0.422081, bits: 0.00955357, dq: 247.992
idf 4.5: 3.16228e-05 ==> 002112: snr: 22.8451, qw: 0.418884, bits: 0.00758884, dq: 314.58
idf 4.6: 2.51189e-05 ==> 002112: snr: 19.2445, qw: 0.416341, bits: 0.00602813, dq: 398.445
idf 4.7: 1.99526e-05 ==> 002112: snr: 16.0584, qw: 0.414318, bits: 0.00478838, dq: 504.055
idf 4.8: 1.58489e-05 ==> 002112: snr: 13.2889, qw: 0.41271, bits: 0.00380359, dq: 637.033
idf 4.9: 1.25893e-05 ==> 002112: snr: 10.9183, qw: 0.411431, bits: 0.00302132, dq: 804.462
idf 5: 1e-05 ==> 021103: snr: 74.4508, qw: 0.212954, bits: 0.00469973, dq: 999.173
idf 5.1: 7.94328e-06 ==> 021103: snr: 62.4172, qw: 0.211694, bits: 0.00373317, dq: 1265.36
idf 5.2: 6.30957e-06 ==> 021103: snr: 51.8642, qw: 0.210692, bits: 0.00296539, dq: 1600.56
idf 5.3: 5.01187e-06 ==> 021103: snr: 42.7625, qw: 0.209895, bits: 0.00235551, dq: 2022.61
idf 5.4: 3.98107e-06 ==> 211012: snr: 23.8183, qw: 0.106581, bits: 0.00366241, dq: 2561.86
idf 5.5: 3.16228e-06 ==> 211012: snr: 20.6233, qw: 0.106001, bits: 0.00290918, dq: 3242.79
idf 5.6: 2.51189e-06 ==> 211012: snr: 17.6438, qw: 0.105541, bits: 0.00231086, dq: 4100.21
idf 5.7: 1.99526e-06 ==> 211012: snr: 14.9286, qw: 0.105175, bits: 0.0018356, dq: 5179.78
idf 5.8: 1.58489e-06 ==> 211012: snr: 12.5058, qw: 0.104884, bits: 0.00145807, dq: 6539.01
idf 5.9: 1.25893e-06 ==> 211012: snr: 10.3842, qw: 0.104653, bits: 0.00115819, dq: 8250.26
idf 6: 1e-06 ==> 211013: snr: 85.5679, qw: 0.104541, bits: 0.000929989, dq: 10285.8
Starting TermTable build.
Total build time: 0.248694 seconds.
===================================
RowAssigner for rank 0
  Terms
    Total: 667747
    Adhoc: 663671
    Explicit: 3703
    Private: 373

  Rows
    Total: 4430
    Adhoc: 1907
    Shared Explicit: 2147
    Private Explicit: 373
    Explicit: 2523

  Bytes per document: 554.125


  Densities in explicit shared rows
    Mean: 0.0893699
    Min: 0.0100032
    Max: 0.099999
    Variance: 0.000386073

===================================
RowAssigner for rank 1
  Terms
    Total: 241594
    Adhoc: 241594
    Explicit: 0
    Private: 0

  Rows
    Total: 1251
    Adhoc: 1251
    Shared Explicit: 0
    Private Explicit: 0
    Explicit: 0

  Bytes per document: 78.1875


  Densities in explicit shared rows
    Mean: nan
    Min: nan
    Max: nan
    Variance: 1

===================================
RowAssigner for rank 2
  Terms
    Total: 642027
    Adhoc: 641661
    Explicit: 0
    Private: 366

  Rows
    Total: 1732
    Adhoc: 1366
    Shared Explicit: 0
    Private Explicit: 366
    Explicit: 366

  Bytes per document: 54.125


  Densities in explicit shared rows
    Mean: nan
    Min: nan
    Max: nan
    Variance: 1

===================================
RowAssigner for rank 3
  Terms
    Total: 597193
    Adhoc: 597193
    Explicit: 0
    Private: 0

  Rows
    Total: 1568
    Adhoc: 1568
    Shared Explicit: 0
    Private Explicit: 0
    Explicit: 0

  Bytes per document: 24.5


  Densities in explicit shared rows
    Mean: nan
    Min: nan
    Max: nan
    Variance: 1

===================================
RowAssigner for rank 4
  Terms
    Total: 416256
    Adhoc: 414832
    Explicit: 0
    Private: 1424

  Rows
    Total: 2903
    Adhoc: 1479
    Shared Explicit: 0
    Private Explicit: 1424
    Explicit: 1424

  Bytes per document: 22.6797


  Densities in explicit shared rows
    Mean: nan
    Min: nan
    Max: nan
    Variance: 1

===================================
RowAssigner for rank 5
  Terms
    Total: 4569
    Adhoc: 4191
    Explicit: 0
    Private: 378

  Rows
    Total: 7241
    Adhoc: 6863
    Shared Explicit: 0
    Private Explicit: 378
    Explicit: 378

  Bytes per document: 28.2852


  Densities in explicit shared rows
    Mean: nan
    Min: nan
    Max: nan
    Variance: 1

===================================
RowAssigner for rank 6
  No terms

Writing TermTable files.
Done.

D:\git\BitFunnel\build-msvc\tools\BitFunnel\src\Release>bitfunnel repl -help
StatisticsBuilder
Ingest documents and compute statistics about them.

Usage:
BitFunnel repl <config>
               [-help]
               [-gramsize <integer>]
               [-threads <integer>]
               [-script <string>]

<config>
    Path to a configuration directory containing files produced
    by the 'BitFunnel statistics' and 'BitFunnel termtable'
    commands. (string)

[-help]
    Display help for this program. (boolean, defaults to false)


[-gramsize <integer>]
    Set the maximum ngram size for phrases. (integer, defaults
    to 1, must be greater than 0)

[-threads <integer>]
    Set the thread count for ingestion and query processing.
    (integer, defaults to 1, must be greater than 0)

[-script <string>]
    File with commands to execute. (string, defaults to NULL)

**Comment by danluu** [comment]
Oh yeah, good catch. I didn't debug this at all.

There's a Lucene crash I need to track down, but after that I'll re-run BitFunnel on GOV2 and post results to the mailing list.
