### ISSUE TITLE
Question about SIGIR2017 publication

### ISSUE THREAD

**Issue by yingfeng** [BitFunnel/BitFunnel#392]
Hi, 
I've found the publication of `ABC: a Fast Signature-File Search Engine` in the accepted paper list of SIGIR2017, it seems to just be the internal design of BitFunnel, is signature file the choice of index design of BitFunnel? Could the publication be attached here for our understanding on such a design choice?

**Comment by MikeHopcroft** [comment]
Thanks for your interest in BitFunnel. The paper you mention is, in fact, about BitFunnel. The title you see on the SIGIR site was the anonymized version of the title used for the peer review. The final title is BitFunnel: Revisiting Signatures for Search. The paper will be available on the ACM website after the conference. I will have to check the ACM rules to see whether it is possible to post it before the conference.

**Comment by yingfeng** [comment]
@MikeHopcroft Thanks for your replying, could you please send the draft to me(via yingfeng.zhang @gmail.com) for an initial review? Thank you!
