### ISSUE TITLE
REPL fails to load index due to buffer size calculations

### ISSUE THREAD

**Issue by jondgoodwin** [BitFunnel/BitFunnel#402]
For example: "Index failed to load" when creating shard 8 (8192 postings). This appears to be because SimpleIndex::StartIndex calculates a m_blocksize of 1048576, which is insufficient for shard 8 where Shard::GetCapacityForByteSize calculated a newBufferSize of 1709184. The m_blocksize is essentially 32 * c_bitsperpage (32768).

Different machines and different experiments need different block sizes. Also, I think we hacked in a fixed block size that worked for the one experiment we were doing. Everyone that has tried to use BitFunnel has stumbled over this issue. The error handling gives no good advice and we have no documentation on choosing a blocksize. 

We should see if we can automate this somewhat and perhaps write a blog post for the cases where the automation does the wrong thing. In production, we adjust the system to use all but about 8GB of physical memory.

**Comment by jondgoodwin** [comment]
Here's a good candidate for explaining this failure: SimpleIndex::StartIndex attempts to estimate a big-enough m_blocksize using the same algorithm/methods later used by Shard::GetCapacityForByteSize, which is wise. However, SimpleIndex only uses *one* termtable (the first) to perform the estimate. 

Since most other termtables take up more room, this estimate is way too low even when arbitrarily bumping it up to a minimum of 1048576. SimpleIndex should instead calculate its estimate using the termtable which requires the most room, which I believe is likely to be the termtable that contains the greatest number of rows.

I recommend replacing this line [tempID=0](  https://github.com/BitFunnel/BitFunnel/blob/master/src/Index/src/SimpleIndex.cpp#L359)

... with a loop that checks all termtables to determine which has the greatest number of rows across all ranks (termTable.GetTotalRowCount(rank)), and then use that termtable to calculate the fixed-size m_blocksize that everything must fit within.

**Comment by MikeHopcroft** [comment]
This seems like a reasonable approach. It would be good if we could use the same algorithm in SimpleIndex::StartIndex() and Shard::GetCapacityForByteSize(). A blog post on the algorithm and its considerations would be useful.

**Comment by jondgoodwin** [comment]
This is fixed by https://github.com/BitFunnel/BitFunnel/pull/409 and https://github.com/BitFunnel/BitFunnel/pull/413.
